sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CATKIN_WS_UNDERLAY=~/catkin_ws_underlay
    - CATKIN_WS_UNDERLAY_SRC=${CATKIN_WS_UNDERLAY}/src
    - CI_ROS_DISTRO="indigo"
    - ROS_PARALLEL_JOBS=-j1
    - DEFAULT_ROSINSTALL="https://raw.githubusercontent.com/squirrel-project/squirrel_calibration/indigo_dev/.rosinstall"

install:
  - bash .travis.sh
